# Generated by Django 6.0.6 on 2026-07-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        help_text="Data da reunião do Conselho Gestor (sexta-feira)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta para pauta"),
                            ("FECHADA", "Fechada"),
                            ("REALIZADA", "Realizada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DIRETORIA", "Diretoria"),
                            ("SECCIONAL", "Seccional"),
                        ],
                        default="DIRETORIA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="PautaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_solicitante", models.CharField(max_length=150)),
                ("email_solicitante", models.EmailField(max_length=254)),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DELIBERATIVA", "Deliberativa"),
                            ("INFORMATIVA", "Informativa"),
                        ],
                        default="DELIBERATIVA",
                        max_length=20,
                    ),
                ),
                (
                    "contexto",
                    models.TextField(
                        help_text="Resumo do assunto para contextualizar o presidente."
                    ),
                ),
                (
                    "link_sei",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Link ou nº do processo SEI",
                    ),
                ),
                (
                    "anexo",
                    models.FileField(blank=True, null=True, upload_to="anexos/%Y/%m/"),
                ),
                (
                    "tempo_solicitado_min",
                    models.PositiveIntegerField(verbose_name="Tempo solicitado (min)"),
                ),
                (
                    "tempo_confirmado_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tempo confirmado (min)"
                    ),
                ),
                (
                    "ordem_apresentacao",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADA", "Enviada"),
                            ("EM_ANALISE", "Em análise pela assessoria"),
                            ("ANALISADA", "Analisada, aguardando deliberação"),
                            ("APROVADA", "Aprovada para o conselho"),
                            ("BACKLOG", "Em backlog"),
                            ("RECUSADA", "Recusada"),
                        ],
                        default="ENVIADA",
                        max_length=20,
                    ),
                ),
                ("parecer_assessoria", models.TextField(blank=True)),
                ("observacao_decisao", models.TextField(blank=True)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("analisado_em", models.DateTimeField(blank=True, null=True)),
                ("decidido_em", models.DateTimeField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="pauta.reuniao",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pautas",
                        to="pauta.unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem_apresentacao", "-enviado_em"],
            },
        ),
    ]
