# Generated by Django 6.0.6 on 2026-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pauta", "0002_seed_unidades_oficiais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidade",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DIRETORIA", "Diretoria"),
                    ("SECCIONAL", "Seccional"),
                    ("CENTRAL", "Unidade central (assessoramento/controle)"),
                ],
                default="DIRETORIA",
                max_length=20,
            ),
        ),
    ]
