# Generated by Django 6.0.6 on 2026-07-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pauta", "0004_ajusta_unidades_centrais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pautaitem",
            name="tempo_solicitado_min",
            field=models.PositiveIntegerField(
                choices=[
                    (5, "5 minutos"),
                    (10, "10 minutos"),
                    (15, "15 minutos"),
                    (30, "30 minutos"),
                ],
                verbose_name="Tempo solicitado (min)",
            ),
        ),
    ]
