# Generated by Django 6.0.6 on 2026-07-05 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pauta", "0005_alter_pautaitem_tempo_solicitado_min"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pautaitem",
            name="anexo",
        ),
    ]
