# Generated by Django 6.0.6 on 2026-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pauta", "0006_remove_pautaitem_anexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pautaitem",
            name="link_sei",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Link ou nº SEI do documento"
            ),
        ),
    ]
